### ISSUE TITLE
Wrong regex rules in SmTSpecifyPackagesNameFilter

### ISSUE THREAD

**Issue by eleonoreW** [eleonoreW/SmartTest#4]
To specify multiple packages for the filter, we have to separate the two regex by a comma instead of a vertical bar.

**Comment by eleonoreW** [comment]
The problem comes from the method SmTSPecifyPackagesNameFilter>>specifyPackage
  ^ ((self packagesRegEx substrings: ',')...
should be replaced by : 
  ^ ((self packagesRegEx substrings: '|')

**Comment by badetitou** [comment]
This piece of code solves the bug and doesn't need substrings and remove one loop

```st
selectedPackage
	^ (RPackageOrganizer default packages
		flatCollect: [ :package | 
			package classTags
				select: [ :classTag | self packagesRegEx asRegex matchesPrefix: classTag categoryName ]
				thenCollect: #categoryName ]) asSet
```

**Comment by eleonoreW** [comment]
Corrected 14/05/2018
